### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by eturner303** [rodschulz/CC72Y_PBA#2]
Hello and thank you for making this repository available.  Have you chosen a license for this project?  If possible, could you upload a LICENSE file to the repository?  I am interested in seeing if I can use this BPA implementation with some Apache or BSD code but am unsure as to your licensing constraints, and do not want to violate them. 

Thank you!

**Comment by rodschulz** [comment]
Hey eturner303,
Sure thing, I could have swear that I had a license here, but it seems I forgot to add one. Thanks for pointing the issue.

I added a GNU v3.0 license, hope that works for you.

Best.
Rodrigo.
